name: Hello World

on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      -  name: Checkout code
         uses: actions/checkout@v3

      -  name: Say Hello
         run: echo "Hello World, GitHub Actions!"
