name: Steps em sequencia

on:
  push:
    branches:
      - main

jobs:
  info-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Data
        run: |
              TZ="America/Sao_Paulo" date +"%Y-%m-%d"

      - name: Get Usuario
        run: |
            AUTHOR=$(git log -1 --pretty=format:%an)
            echo "O autor do commit é: $AUTHOR"

      - name: Arquivos HTML
        run: ls | grep '\.html$' | wc -l

      - name: Arquivos CSS
        run: ls | grep '\.css$' | wc -l

      - name: Arquivos JS
        run: ls | grep '\.js$' | wc -l
