name: Criar README automático

permissions:
  contents: write

on:
  push:
    branches: [main]

jobs:
  arquivo-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Criar README.md automático
        run: |
          echo "# Gerando Readme.md automaticamente" > README.md
          echo "" >> README.md
          echo "## GitHub Actions" >> README.md
          echo "thiago santos RA: 240055" >> README.md

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commitar mudanças
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Atualizando README.md automaticamente" || echo "Nenhuma mudança para commitar"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
