name: Mostrar usuario

on:
  push:
    branches:
      - main

jobs:
  usuario:
    runs-on: ubuntu-latest

    steps:
     - name: Usuario checkout
       uses: actions/checkout@v4

     - name: Get Usuario
       run: |
            AUTHOR=$(git log -1 --pretty=format:%an)
            echo "O autor do commit é: $AUTHOR"
