name: Usu치rio do push

on:
  push:
    branches: [main]

jobs:
  user:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v3

      - name: Mostrar usu치rio do push
        run: echo "Usu치rio do GitHub: ${{ github.actor }}"
